### ISSUE TITLE
add "ignore Reverb Zone" to UserJoinLeave sounds

### ISSUE THREAD

**Issue by epicEaston197** [badhaloninja/UserJoinLeaveNotifications#4]
sometimes when I'm in Worlds that have a Reverb Zone it can cause the sound to Reverb

**Comment by badhaloninja** [comment]
It already ignores reverb any notification panel sound does

**Comment by epicEaston197** [comment]
> It already ignores reverb any notification panel sound does

okay cool I did think it sounded a little odd and 72 Grove Lake
