### ISSUE TITLE
(bug) user join leave sounds sound distorted

### ISSUE THREAD

**Issue by epicEaston197** [badhaloninja/UserJoinLeaveNotifications#5]
whenever someone joins the session the audio sounds like it's pitched up

join sound
neosdb:///7fdd0089c11d3c988e9b7a2a15aa60c43eb5383a40d62e8f04d9a876b2f62c97

leave sound
neosdb:///967ff06a6cc3f3123c97a6a4d40255deb9c5a6c5b626460ff3f9a443f57d1d5a

https://user-images.githubusercontent.com/76523692/189240837-6c367270-3785-4d70-92e3-bed4d7b567ed.mp4

here's another video demonstrating how it sounds normally

https://user-images.githubusercontent.com/76523692/189241372-b9f03fd5-2a2b-493b-969d-11350ac9afa4.mp4

**Comment by Banane9** [comment]
This is because the clip gets played at a random speed between .95x and 1.05x

![Call to PlayOneshot in AddNotification()](https://user-images.githubusercontent.com/2124570/192899544-d2276fcf-8bd2-4994-988e-ebd793ce7113.png)

**Comment by badhaloninja** [comment]
Fixed in v2.0.0
