### ISSUE TITLE
user join leave sounds does not respect user interface volume

### ISSUE THREAD

**Issue by epicEaston197** [badhaloninja/UserJoinLeaveNotifications#8]
That's about it it's annoying

I feel like the volume inputs should still take into account for the user interface volume

**Comment by badhaloninja** [comment]
The sound is properly adjusted by the user interface volume for me?

Also this is the wrong repo, please recreate this on https://github.com/badhaloninja/UserJoinLeaveNotifications

**Comment by badhaloninja** [comment]
Actually turns out there's a button for that

**Comment by epicEaston197** [comment]
okay maybe it does I don't know pretty hard to test the behavior when people don't join very often

**Comment by badhaloninja** [comment]
Is this still the observed behavior?

**Comment by epicEaston197** [comment]
I would have to do purposeful testing I just haven't noticed it yet

**Comment by epicEaston197** [comment]
okay I'm closing this issue as it's been solved
